Add title when adding public keys
warp-tech/warpgate pull request #1171
Opened 2024-12-14 23:50 UTC by moalshak

This PR adds the title input as a field in the frontend and saves it in the DB.

A view from the modal:

<img width="504" alt="Screenshot 2024-12-15 at 12 43 59 AM" src="https://github.com/user-attachments/assets/ffaf3fa2-1556-4033-b2a9-09947184b473" />

Public key after being saved:

<img width="1320" alt="Screenshot 2024-12-15 at 12 46 21 AM" src="https://github.com/user-attachments/assets/38421627-5d16-4fdb-b9f6-1cee85a6f29f" />

Working on this, I realized that we should probably add more metadata like when it was added, when it was last used etc.

Fixes: https://github.com/warp-tech/warpgate/issues/714, https://github.com/warp-tech/warpgate/issues/754, https://github.com/warp-tech/warpgate/issues/898

One thing to note is that my passwords manager stopped recognizing the public id field as one.

2024-12-15 00:00 UTC, Eugeny requested changes
Thank you for the PR!

> Working on this, I realized that we should probably add more metadata like when it was added, when it was last used etc.

That's a great idea - happy to merge if you're willing to work on this.

> passwords manager stopped recognizing the public id field as one.

What does this mean?

2024-12-15 00:00 UTC, Eugeny commented on warpgate-admin/src/api/public_key_credentials.rs
> +    openssh_public_key_title: String,
Please rename the field into just `label` (it makes more sense than `title`, and `openssh` refers to the public key format).

2024-12-15 00:00 UTC, Eugeny commented on warpgate-protocol-http/src/api/credentials.rs
> +    openssh_public_key_title: String,
same here

2024-12-15 00:00 UTC, Eugeny commented on warpgate-web/src/admin/PublicKeyCredentialModal.svelte
> +            Add new SSH Public Key
```suggestion
            Add an SSH public key
```

2024-12-15 00:10 UTC, moalshak commented
> What does this mean?

My 1Password used to recognize the field as an ssh field and suggest adding my saved pub key in it.

![image](https://github.com/user-attachments/assets/05381f28-cd4c-418e-a73d-7faf03f595a3)

2024-12-15 00:12 UTC, moalshak commented on warpgate-protocol-http/src/api/credentials.rs
> +    openssh_public_key_title: String,
In the frontend as well?

2024-12-15 00:12 UTC, Eugeny commented
Oh - I wonder what logic it uses to recognize it.

2024-12-15 00:13 UTC, Eugeny commented on warpgate-protocol-http/src/api/credentials.rs
> +    openssh_public_key_title: String,
yes

2024-12-15 00:13 UTC, moalshak commented
> Oh - I wonder what logic it uses to recognize it.

Not great logic tbh haha, since it thinks the title input is the ssh input on the https://github.com/settings/ssh/new page.

2024-12-17 23:12 UTC, Eugeny commented
You can ignore the sonarqube error - however the migration is failing when there are existing keys in the database:

```23:11:50 ERROR Fatal error error=Execution Error: error returned from database: (code: 1) Cannot add a NOT NULL column with default value NULL```

2024-12-18 08:46 UTC, moalshak commented
@Eugeny I fixed that (locally). However, I am running into issues now due to the name "label". Since for the user's view of the profile, that field was already being used for the abbreviated ssh key. See:

<img width="389" alt="Screenshot 2024-12-18 at 9 45 35 AM" src="https://github.com/user-attachments/assets/a438e7de-2afc-42b4-96ae-7dfc81bf4e1a" />

<img width="544" alt="Screenshot 2024-12-18 at 9 45 49 AM" src="https://github.com/user-attachments/assets/7a6034f7-1fba-41d1-984f-06951df47267" />


What do you propose to change ? The name from label to back to title ? Or the old label to abbreviation?

2024-12-18 09:35 UTC, Eugeny commented
Let's change the old `label` to `abbreviated`

2024-12-18 20:53 UTC, Eugeny commented
Looks good now - thanks!

@all-contributors add @moalshak for code

2024-12-18 20:53 UTC, merged